version: '2'
services:
  app:
    build: .
    ports:
      - "9292:9292"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_ENV=development
    depends_on:
      - redis
    volumes:
      - .:/myapp
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"